"""Generate publication-sized plots and evidence tables from actual run outputs."""
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

NAVY, TEAL, GOLD, GRAY = "#142d42", "#168b88", "#d89b36", "#778797"
LABELS = {"last_week": "Last week", "mean_4": "Four-week mean", "annual_52": "Last year / fallback",
          "selected_ml": "Selected boosted model", "deployed": "Validation winner",
          "mean4": "Four-week mean", "mean4_tuned": "Mean + tuned buffer", "point": "Point forecast",
          "point_tuned": "Point + tuned buffer", "quantile_80": "80th-percentile stock"}


def table(frame: pd.DataFrame) -> str:
    def fmt(value):
        return f"{value:,.3f}" if isinstance(value, (float, np.floating)) else str(value)
    lines = ["| " + " | ".join(frame.columns) + " |", "| " + " | ".join("---" for _ in frame.columns) + " |"]
    lines += ["| " + " | ".join(fmt(x) for x in row) + " |" for row in frame.itertuples(index=False, name=None)]
    return "\n".join(lines)


def plots(output: Path, forecasts: pd.DataFrame, costs: pd.DataFrame, predictions: pd.DataFrame,
          weekly: pd.DataFrame, sample_sku: str, names: dict):
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10, "axes.spines.top": False,
        "axes.spines.right": False, "axes.titleweight": "bold", "axes.labelcolor": NAVY,
        "text.color": NAVY, "axes.edgecolor": "#cbd4dc", "figure.facecolor": "white"})
    fig, axes = plt.subplots(1, 2, figsize=(12.8, 4.8), layout="constrained")
    f = forecasts.loc[forecasts.model != "deployed"]
    axes[0].barh([LABELS.get(x, x) for x in f.model], f.wape * 100, color=[GRAY, GRAY, GRAY, TEAL])
    axes[0].invert_yaxis()
    axes[0].set(xlabel="WAPE (%) · lower is better", title="Forecast accuracy")
    for i, v in enumerate(f.wape * 100):
        axes[0].text(v + 0.5, i, f"{v:.1f}%", va="center", fontsize=9)
    axes[0].set_xlim(0, f.wape.max() * 125)
    axes[1].barh([LABELS.get(x, x) for x in costs.policy], costs.total_cost / 1000,
                 color=[GRAY, NAVY, GRAY, NAVY, TEAL])
    axes[1].invert_yaxis()
    axes[1].set(xlabel="Illustrative cost (thousands) · lower is better", title="Stock decisions · 4:1 shortage penalty")
    for i, v in enumerate(costs.total_cost / 1000):
        axes[1].text(v + 1, i, f"{v:.1f}", va="center", fontsize=9)
    axes[1].set_xlim(0, costs.total_cost.max() / 1000 * 1.22)
    fig.suptitle("ShelfCast | 50 products · 13 held-out weeks", fontsize=16, fontweight="bold")
    fig.savefig(output / "benchmark.png", dpi=170, bbox_inches="tight")
    plt.close(fig)

    example = predictions.loc[predictions.sku == sample_sku]
    fig, ax = plt.subplots(figsize=(11.5, 4.3), layout="constrained")
    ax.fill_between(example.week, example.lower, example.upper, color=TEAL, alpha=0.15, label="Calibrated 80% range")
    ax.plot(example.week, example.units, "o-", color=NAVY, label="Recorded sales", linewidth=2)
    ax.plot(example.week, example.point, "--", color=TEAL, label="Point forecast", linewidth=2)
    ax.plot(example.week, example.q80, ":", color=GOLD, label="80th-percentile stock target", linewidth=2)
    ax.set(ylabel="Units per week", xlabel="Forecast week (Monday)", ylim=(0, None),
           title=f"{sample_sku} · {names.get(sample_sku, sample_sku).title()}\nProduct chosen by median training sales rank")
    ax.legend(loc="upper right", fontsize=9, ncol=2)
    fig.savefig(output / "forecast_example.png", dpi=170, bbox_inches="tight")
    plt.close(fig)

    fig, axes = plt.subplots(2, 1, figsize=(11.5, 6), sharex=True, layout="constrained")
    axes[0].plot(weekly.week, weekly.wape * 100, "o-", color=NAVY)
    axes[0].set(ylabel="Weekly WAPE (%)", title="Performance over time · frozen model, refreshed past-only features")
    axes[1].plot(weekly.week, weekly.coverage * 100, "o-", color=TEAL, label="Observed interval coverage")
    axes[1].axhline(80, color=GOLD, linestyle="--", label="Nominal 80%")
    axes[1].set(ylabel="Coverage (%)", xlabel="Forecast week (Monday)", ylim=(0, 105))
    axes[1].legend(loc="lower left")
    fig.savefig(output / "weekly_monitoring.png", dpi=170, bbox_inches="tight")
    plt.close(fig)


def write_report(output: Path, forecast: pd.DataFrame, costs: pd.DataFrame, intervals: dict,
                 bootstrap: dict, metadata: dict, audit: dict):
    effect = bootstrap["relative_cost_reduction"] * 100
    low, high = [v * 100 for v in bootstrap["bootstrap_95_percentile_interval"]]
    text = f"""# ShelfCast experiment report

This report was generated by `shelfcast reproduce` from the committed weekly sales panel.
It evaluates one-week-ahead forecasts on **{audit['cohort_products']} products and 13 weeks**
(2011-09-05 through 2011-11-28). Data are real recorded sales; inventory costs are hypothetical.

## Forecast performance

{table(forecast)}

WAPE is total absolute error divided by total recorded units. MAE is in units per product-week.
The deployment model **{metadata['selected_point_model']}** was selected on validation WAPE;
**{metadata['selected_ml_model']}** was the best boosted candidate on validation.
The `deployed` row intentionally repeats a baseline or the selected ML row when they are the same model.
No test outcome is used to choose a model, product cohort, or multiplier.

## Uncertainty

- Nominal central interval coverage: 80%.
- Raw quantile coverage: **{intervals['raw']['coverage']:.1%}**; mean width **{intervals['raw']['mean_width']:.1f} units**.
- Calibrated coverage: **{intervals['calibrated']['coverage']:.1%}**; mean width **{intervals['calibrated']['mean_width']:.1f} units**.
- Raw 80th-quantile empirical coverage: **{intervals['q80_empirical_coverage']:.1%}**.

Calibration uses a separate July–August block and scales residuals by past eight-week mean sales.
Products share market conditions and observations are ordered in time, so the exchangeability
assumption of standard split conformal prediction is not justified. These are **empirical results,
not a guaranteed service level**. Weekly monitoring shows whether aggregate metrics hide deterioration.

## Inventory decision benchmark

{table(costs)}

Each product-week is an independent single-period stock decision with zero opening stock,
immediate replenishment, no capacity limit, and no carryover. Targets are rounded upward to
whole units. Cost = `4 × shortage units + 1 × excess units`. The numbers are scenario cost units,
not observed pounds, profit, or achieved business savings. Fill rate is fulfilled units / recorded units;
it differs from the fraction of product-weeks without a shortage.

The quantile policy's relative cost reduction versus the **validation-tuned four-week-mean policy**
is **{effect:+.1f}%** (negative means it costs more). A paired moving-block bootstrap gives a
descriptive 95% percentile interval of **[{low:+.1f}%, {high:+.1f}%]**, resampling three consecutive
weeks at a time with all products together, for 2,000 draws. Thirteen test weeks are too few to
establish generalization to other seasons, retailers, or cost ratios.

## Reproduction evidence

- Source workbook SHA-256: `{audit.get('source_sha256', 'see data/audit.json')}`.
- Panel SHA-256: `{metadata['panel_sha256']}`.
- Source-code SHA-256: `{metadata['source_sha256']}`.
- Model identifier: `{metadata['model_id']}`.
- Runtime: {metadata['runtime_seconds']:.1f} seconds on the recorded environment (excludes original workbook parsing).
- Full parameters, split boundaries, dependency versions, and selection scores: `run_metadata.json`.
- Row-level holdout forecasts: `predictions.csv`; per-week results: `weekly_metrics.csv`.
- Decision replay: `decision_details.csv`; cost-ratio sensitivity: `cost_sensitivity.csv`.

## Limits that affect interpretation

The cohort contains active, high-volume UK products selected on the training period. It does not
represent all products or cold starts. No-transaction weeks are filled with zero recorded sales;
the dataset cannot distinguish zero demand from unavailable stock or delisting. Returns and
cancellations are excluded rather than netted, and genuine bulk orders are retained. The final
test block contains the autumn shopping season; it is intentionally not a random row split.

See [the design document](../docs/design.md) and [data attribution](../data/README.md).
"""
    (output / "RESULTS.md").write_text(text)
